[package]
name = "cdc-comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
fastcdc = "3.0.3"
walkdir = "2.3.3"
ring = "0.16.20"
data-encoding = "2.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
markdown-table = "0.2.0"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
